# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild -project epanel.xcodeproj -scheme epanel -sdk macosx -configuration Release build
    - name: Run tests
      run: xcodebuild test -project epanel.xcodeproj -scheme epanel -sdk macosx -configuration Debug -destination 'platform=macOS'

